# Generated by Django 2.2.3 on 2019-10-04 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking', models.CharField(max_length=255)),
                ('booking_id', models.IntegerField()),
                ('booking_city', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('mobile', models.CharField(max_length=15)),
                ('message', models.TextField(blank=True)),
                ('experience', models.TextField(blank=True)),
                ('dance_school', models.CharField(max_length=255)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('user_id', models.IntegerField(blank=True)),
                ('contact_city', models.CharField(max_length=255)),
            ],
        ),
    ]
