# Generated by Django 2.2.3 on 2019-08-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20190810_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='booking_city',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='contact_city',
            field=models.CharField(default='manchester', max_length=255),
            preserve_default=False,
        ),
    ]
