# Generated by Django 2.2.3 on 2019-10-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, default='static/img/default-teachers-pic.jpg', upload_to='photos/%Y/%m/%d/')),
                ('city', models.CharField(choices=[('aberdeen', 'Aberdeen'), ('bath', 'Bath'), ('birmingham', 'Birmingham'), ('blackburn', 'Blackburn'), ('blackpool', 'Blackpool'), ('bournemouth', 'Bournemouth'), ('bradford', 'Bradford'), ('brighton', 'Brighton'), ('bristol', 'Bristol'), ('cambridge', 'Cambridge'), ('canterbury', 'Canterbury'), ('cardiff', 'Cardiff'), ('chester', 'Chester'), ('coventry', 'Coventry'), ('darlington', 'Darlington'), ('derby', 'Derby'), ('doncaster', 'Doncaster'), ('dundee', 'Dundee'), ('durham', 'Durham'), ('edinburgh', 'Edinburgh'), ('exeter', 'Exeter'), ('glasgow', 'Glasgow'), ('guildford', 'Guildford'), ('harrogate', 'Harrogate'), ('huddersfield', 'Huddersfield'), ('hull', 'Hull'), ('leeds', 'Leeds'), ('leicester', 'Leicester'), ('liverpool', 'Liverpool'), ('london', 'London'), ('manchester', 'Manchester'), ('newcastle', 'Newcastle'), ('northampton', 'Northampton'), ('norwich', 'Norwich'), ('nottingham', 'Nottingham'), ('oxford', 'Oxford'), ('portsmouth', 'Portsmouth'), ('preston', 'Preston'), ('reading', 'Reading'), ('sheffield', 'Sheffield'), ('southampton', 'Southampton'), ('stoke', 'stoke'), ('sunderland', 'Sunderland'), ('swansea', 'Swansea'), ('york', 'York')], default=None, max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('speciality', models.TextField()),
                ('fee', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('dance_school_attended', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
