# Generated by Django 2.2.3 on 2019-08-01 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=200)),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('postcode', models.CharField(blank=True, max_length=10)),
                ('speciality', models.TextField()),
                ('fee', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('dance_school_attended', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
