# Generated by Django 2.2.3 on 2019-08-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(choices=[('brighton', 'Brighton'), ('leeds', 'Leeds'), ('liverpool', 'Liverpool'), ('manchester', 'Manchester')], default=None, max_length=100),
        ),
    ]
