# Generated by Django 2.2.3 on 2019-08-10 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20190801_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(choices=[('bath', 'Bath'), ('brighton', 'Brighton'), ('leeds', 'Leeds'), ('liverpool', 'Liverpool'), ('manchester', 'Manchester')], default=None, max_length=100),
        ),
    ]
