# Generated by Django 2.2.3 on 2019-08-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_auto_20190810_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='city',
            field=models.CharField(choices=[('aberdeen', 'Aberdeen'), ('bath', 'Bath'), ('birmingham', 'Birmingham'), ('blackburn', 'Blackburn'), ('blackpool', 'Blackpool'), ('bournemouth', 'Bournemouth'), ('bradford', 'Bradford'), ('brighton', 'Brighton'), ('bristol', 'Bristol'), ('cambridge', 'Cambridge'), ('canterbury', 'Canterbury'), ('cardiff', 'Cardiff'), ('chester', 'Chester'), ('coventry', 'Coventry'), ('darlington', 'Darlington'), ('derby', 'Derby'), ('doncaster', 'Doncaster'), ('dundee', 'Dundee'), ('durham', 'Durham'), ('edinburgh', 'Edinburgh'), ('exeter', 'Exeter'), ('glasgow', 'Glasgow'), ('guildford', 'Guildford'), ('harrogate', 'Harrogate'), ('huddersfield', 'Huddersfield'), ('hull', 'Hull'), ('leeds', 'Leeds'), ('leicester', 'Leicester'), ('liverpool', 'Liverpool'), ('london', 'London'), ('manchester', 'Manchester'), ('newcastle', 'Newcastle'), ('northampton', 'Northampton'), ('norwich', 'Norwich'), ('nottingham', 'Nottingham'), ('oxford', 'Oxford'), ('portsmouth', 'Portsmouth'), ('preston', 'Preston'), ('reading', 'Reading'), ('sheffield', 'Sheffield'), ('southampton', 'Southampton'), ('stoke', 'stoke'), ('sunderland', 'Sunderland'), ('swansea', 'Swansea'), ('york', 'York')], default=None, max_length=100),
        ),
    ]
