# Generated by Django 2.2.3 on 2019-08-08 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20190801_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='photo_1',
            field=models.ImageField(blank=True, upload_to='photos/venue/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo_2',
            field=models.ImageField(blank=True, upload_to='photos/venue/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='venue',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='photos/venue/%Y/%m/%d/'),
        ),
    ]
