# Generated by Django 2.2.3 on 2019-10-04 20:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teachers', '0001_initial'),
        ('styles', '0001_initial'),
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13)),
                ('initial_chat', models.BooleanField(default=False)),
                ('event_date', models.DateField()),
                ('event_length', models.CharField(choices=[('1', '1hr'), ('1.5', '1.5hrs')], default=None, max_length=5)),
                ('booking_quantity', models.DecimalField(decimal_places=1, max_digits=2)),
                ('book_before_date', models.DateField()),
                ('start_time', models.CharField(blank=True, max_length=10)),
                ('end_time', models.CharField(blank=True, max_length=10)),
                ('special_person', models.CharField(blank=True, max_length=80)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('enquiry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('venue_booked', models.BooleanField(default=False)),
                ('venue_paid', models.BooleanField(default=False)),
                ('teacher_fee', models.IntegerField(blank=True, null=True)),
                ('teacher_confirmed', models.BooleanField(default=False)),
                ('teacher_texted', models.BooleanField(default=False)),
                ('teacher_paid', models.BooleanField(default=False)),
                ('cost', models.IntegerField(blank=True)),
                ('discount', models.IntegerField(blank=True)),
                ('venue_cost', models.IntegerField(blank=True, null=True)),
                ('is_advertised', models.BooleanField(default=False)),
                ('workshop_booked', models.BooleanField(default=False)),
                ('booking_sent', models.BooleanField(default=False)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('agency', models.BooleanField(default=False)),
                ('balance_paid', models.BooleanField(default=False)),
                ('problem', models.BooleanField(default=False)),
                ('booking_notes', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities.City')),
                ('confirmed_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='confirmed_venue', to='cities.Venue')),
                ('dance_style', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='styles.Style')),
                ('dance_style2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_dance', to='styles.Style')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher')),
                ('venue_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue_1', to='cities.Venue')),
                ('venue_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue_2', to='cities.Venue')),
                ('venue_3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue_3', to='cities.Venue')),
                ('venue_4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='venue_4', to='cities.Venue')),
            ],
        ),
    ]
