# Generated by Django 2.2.3 on 2019-08-01 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('styles', '0001_initial'),
        ('cities', '0003_auto_20190801_1402'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('initial_chat', models.BooleanField(default=False)),
                ('event_date', models.DateField()),
                ('book_before_date', models.DateField()),
                ('start_time', models.CharField(blank=True, max_length=10)),
                ('end_time', models.CharField(blank=True, max_length=10)),
                ('special_person', models.CharField(blank=True, max_length=80)),
                ('group_size', models.IntegerField(blank=True, null=True)),
                ('enquiry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('venue_booked', models.BooleanField(default=False)),
                ('venue_paid', models.BooleanField(default=False)),
                ('teacher_fee', models.IntegerField(blank=True, null=True)),
                ('teacher_confirmed', models.BooleanField(default=False)),
                ('teacher_texted', models.BooleanField(default=False)),
                ('teacher_paid', models.BooleanField(default=False)),
                ('cost', models.IntegerField(blank=True)),
                ('workshop_booked', models.BooleanField(default=False)),
                ('deposit_paid', models.BooleanField(default=False)),
                ('agency', models.BooleanField(default=False)),
                ('balance_paid', models.BooleanField(default=False)),
                ('problem', models.BooleanField(default=False)),
                ('booking_notes', models.TextField(blank=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities.City')),
                ('dance_style', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='styles.Style')),
                ('dance_style2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_dance', to='styles.Style')),
                ('studio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cities.Studio')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='teachers.Teacher')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cities.Venue')),
                ('venue_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='potential_venue', to='cities.Venue')),
                ('venue_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='backup_venue', to='cities.Venue')),
            ],
        ),
    ]
