# Generated by Django 2.2.3 on 2019-10-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_auto_20191004_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='discount',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
