# Generated by Django 2.2.3 on 2019-08-13 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_auto_20190806_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_advertised',
            field=models.BooleanField(default=False),
        ),
    ]
