# Generated by Django 2.2.3 on 2019-08-01 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dance_style', models.CharField(help_text='Enter Dance Style', max_length=200)),
            ],
        ),
    ]
